//! Brand-icon registry: Simple Icons path data (ADR-0005 decision 6).
//!
//! `data/simple-icons.tsv` is generated by `scripts/update-simple-icons.py`
//! from the Simple Icons npm release (CC0-1.0 path data; brand names and logos
//! remain trademarks of their owners). Every glyph is one SVG path on a 24×24
//! viewBox. The table is parsed once, on first use, into a lookup map.

use std::collections::HashMap;
use std::sync::OnceLock;

const DATA: &str = include_str!("../../../../data/simple-icons.tsv");

/// One Simple Icons glyph: a single path on a 24×24 viewBox.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct BrandIcon {
    pub slug: &'static str,
    pub title: &'static str,
    /// Brand color, six uppercase hex digits without `#`.
    pub hex: &'static str,
    /// SVG path data (`d`), viewBox `0 0 24 24`.
    pub path: &'static str,
}

struct Registry {
    icons: Vec<BrandIcon>,
    by_key: HashMap<&'static str, usize>,
    version: &'static str,
}

fn registry() -> &'static Registry {
    static REGISTRY: OnceLock<Registry> = OnceLock::new();
    REGISTRY.get_or_init(|| {
        let mut icons = Vec::with_capacity(3600);
        let mut alts: Vec<(&'static str, usize)> = Vec::new();
        let mut version = "unknown";
        for line in DATA.lines() {
            if let Some(header) = line.strip_prefix("# simple-icons ") {
                version = header.split_whitespace().next().unwrap_or(version);
                continue;
            }
            let mut cols = line.split('\t');
            let (Some(slug), Some(hex), Some(title), Some(alt), Some(path)) = (
                cols.next(),
                cols.next(),
                cols.next(),
                cols.next(),
                cols.next(),
            ) else {
                continue;
            };
            let index = icons.len();
            icons.push(BrandIcon {
                slug,
                title,
                hex,
                path,
            });
            alts.extend(alt.split(',').filter(|k| !k.is_empty()).map(|k| (k, index)));
        }
        let mut by_key: HashMap<&'static str, usize> = icons
            .iter()
            .enumerate()
            .map(|(i, icon)| (icon.slug, i))
            .collect();
        for (key, index) in alts {
            by_key.entry(key).or_insert(index);
        }
        Registry {
            icons,
            by_key,
            version,
        }
    })
}

/// Simple Icons' `titleToSlug`: lowercase, `+`→plus, `.`→dot, `&`→and, a few
/// letter folds, then keep only `[a-z0-9]`.
pub(crate) fn title_to_slug(title: &str) -> String {
    let mut out = String::with_capacity(title.len());
    for ch in title.chars().flat_map(char::to_lowercase) {
        match ch {
            '+' => out.push_str("plus"),
            '.' => out.push_str("dot"),
            '&' => out.push_str("and"),
            'ß' => out.push_str("ss"),
            'đ' => out.push('d'),
            'ħ' => out.push('h'),
            'ı' => out.push('i'),
            'ĸ' => out.push('k'),
            'ŀ' | 'ł' => out.push('l'),
            'ŧ' => out.push('t'),
            c if c.is_ascii_alphanumeric() => out.push(c),
            _ => {}
        }
    }
    out
}

/// Look a brand up by slug (`nodedotjs`), title (`Node.js`), a Simple Icons
/// alias title (`Twitter` → `x`), or the slug without `dot` (`nodejs`).
///
/// This is the shared lookup for every surface that paints a brand glyph
/// (strip, icon tiles, badge `logo=`): path data on a 24×24 viewBox plus the
/// brand hex.
pub(crate) fn lookup(raw: &str) -> Option<BrandIcon> {
    let reg = registry();
    let trimmed = raw.trim();
    let exact = trimmed.to_ascii_lowercase();
    let found = reg.by_key.get(exact.as_str()).or_else(|| {
        let slug = title_to_slug(trimmed);
        reg.by_key.get(slug.as_str())
    })?;
    reg.icons.get(*found).copied()
}

/// Number of embedded brand glyphs.
pub(crate) fn count() -> usize {
    registry().icons.len()
}

/// Embedded Simple Icons release version.
pub(crate) fn version() -> &'static str {
    registry().version
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_loads_the_full_release() {
        assert!(count() > 3000, "only {} icons loaded", count());
        assert_ne!(version(), "unknown");
    }

    #[test]
    fn lookup_by_slug_title_alias_and_dotless() {
        assert_eq!(lookup("rust").unwrap().slug, "rust");
        assert_eq!(lookup("Node.js").unwrap().slug, "nodedotjs");
        assert_eq!(lookup("nodejs").unwrap().slug, "nodedotjs");
        assert_eq!(lookup("C++").unwrap().slug, "cplusplus");
        assert_eq!(lookup("Twitter").unwrap().slug, "x");
        assert_eq!(lookup("  TypeScript ").unwrap().hex, "3178C6");
        assert!(lookup("not-a-brand-at-all").is_none());
        assert!(lookup("").is_none());
    }

    #[test]
    fn glyphs_are_plain_path_data() {
        for icon in &registry().icons {
            assert_eq!(icon.hex.len(), 6, "{}", icon.slug);
            assert!(icon.hex.bytes().all(|b| b.is_ascii_hexdigit()));
            assert!(
                !icon.path.contains(['"', '<', '>', '&']),
                "{} path must be attribute-safe",
                icon.slug
            );
        }
    }

    #[test]
    fn title_to_slug_matches_simple_icons() {
        assert_eq!(title_to_slug("Node.js"), "nodedotjs");
        assert_eq!(title_to_slug("1&1"), "1and1");
        assert_eq!(title_to_slug("Notepad++"), "notepadplusplus");
    }
}
